# Generated by Django 6.0.4 on 2026-04-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_confirmed",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_new",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.city",
                verbose_name="Город",
            ),
        ),
    ]
