name: main_env
values:
  - key: baseUrl
    value: 'http://127.0.0.1:8000'
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
  - key: email
    value: ''
  - key: password
    value: ''
