# Generated by Django 6.0.4 on 2026-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="products/images/default.png", upload_to="products/"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
