# Generated by Django 6.0.4 on 2026-04-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_image_delete_productimage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
