# Generated by Django 6.0.4 on 2026-04-27 09:28

import django.core.validators
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_subcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/images/default.png",
                upload_to="products/",
                validators=[catalog.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
    ]
